"""
mission_control/nominal_compare.py
------------------------------------
Compares real-time telemetry against the pre-computed nominal trajectory,
determines mission phase, assesses go/no-go gates, and generates
pitch/roll correction advisories.

This module is the "flight controller" logic layer: everything it does is
pure computation, with no I/O. The server module calls it on each telemetry
update and relays results to connected browsers.

Exports:
    NominalTrajectory   Precomputed nominal trajectory with lookup methods
    FlightPhase         Enum of mission phases
    Advisory            Dataclass for a pilot correction advisory
    GoNoGo              Dataclass for a go/no-go gate assessment
    FlightDirector      Main comparison + advisory engine
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

# ---------------------------------------------------------------------------
# Enums and data classes
# ---------------------------------------------------------------------------

class FlightPhase(Enum):
    PRELAUNCH    = "PRELAUNCH"
    BOOST        = "BOOST"          # SRBs burning
    CORE         = "CORE"           # Swivel only, post-sep
    TERRIER      = "TERRIER"        # Mission stage / Terrier burning
    CIRCULARIZE  = "CIRCULARIZE"    # Near apoapsis, circularizing
    ORBIT        = "ORBIT"          # Stable orbit
    TMI          = "TMI"            # Trans-Mun Injection burn
    COAST        = "COAST"          # Ballistic coast
    UNKNOWN      = "UNKNOWN"


@dataclass
class Advisory:
    """A pilot correction advisory generated by the flight director."""
    level:     str          # 'NOMINAL', 'CAUTION', 'WARNING', 'ABORT'
    action:    str          # Short imperative: 'PITCH DOWN 8°'
    reason:    str          # Explanation: 'Apoapsis stalling — build horizontal speed'
    urgent:    bool = False


@dataclass
class GateStatus:
    """Status of a single go/no-go gate."""
    phase:    str
    status:   str   # 'GO', 'MARGINAL', 'NO-GO', 'NOT-YET'
    detail:   str


# ---------------------------------------------------------------------------
# Nominal trajectory lookup
# ---------------------------------------------------------------------------

class NominalTrajectory:
    """
    Precomputed nominal trajectory with interpolation by time or altitude.
    Loaded once at server startup.
    """

    def __init__(self, points: list):
        """
        Parameters
        ----------
        points : list of TrajectoryPoint
            From sim.run_ascent().points
        """
        self._pts = points  # sorted by t

    @classmethod
    def load(cls) -> NominalTrajectory:
        """Run the sim and return a NominalTrajectory."""
        import sys, os
        sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
        from sim import run_ascent
        result = run_ascent()
        return cls(result.points)

    def at_time(self, t: float) -> Optional[dict]:
        """Return interpolated nominal state at mission elapsed time t (s)."""
        pts = self._pts
        if not pts or t < pts[0].t:
            return None
        for i in range(len(pts) - 1):
            if pts[i].t <= t <= pts[i + 1].t:
                f = (t - pts[i].t) / (pts[i + 1].t - pts[i].t)
                return self._interp(pts[i], pts[i + 1], f)
        return self._pt_to_dict(pts[-1])

    def at_altitude(self, alt_m: float) -> Optional[dict]:
        """Return interpolated nominal state at altitude alt_m (m)."""
        pts = self._pts
        if not pts:
            return None
        for i in range(len(pts) - 1):
            a0, a1 = pts[i].altitude, pts[i + 1].altitude
            if min(a0, a1) <= alt_m <= max(a0, a1):
                if abs(a1 - a0) < 1.0:
                    return self._pt_to_dict(pts[i])
                f = (alt_m - a0) / (a1 - a0)
                return self._interp(pts[i], pts[i + 1], f)
        return None

    def trajectory_for_plot(self) -> list:
        """Return trajectory as list of dicts for JSON serialization."""
        return [
            {
                "t": p.t,
                "altitude_km": p.altitude / 1000.0,
                "downrange_km": p.downrange / 1000.0,
                "velocity": p.velocity,
                "apoapsis_km": p.apoapsis,
                "periapsis_km": p.periapsis,
                "pitch_from_vertical": p.pitch_from_v,
                "phase": p.phase,
            }
            for p in self._pts
        ]

    def _pt_to_dict(self, p) -> dict:
        return {
            "t": p.t,
            "altitude_km": p.altitude / 1000.0,
            "downrange_km": p.downrange / 1000.0,
            "velocity": p.velocity,
            "v_horiz": p.v_horiz,
            "v_vert": p.v_vert,
            "apoapsis_km": p.apoapsis,
            "periapsis_km": p.periapsis,
            "pitch_from_vertical": p.pitch_from_v,
        }

    def _interp(self, p0, p1, f: float) -> dict:
        def lerp(a, b): return a + (b - a) * f
        return {
            "t": lerp(p0.t, p1.t),
            "altitude_km": lerp(p0.altitude, p1.altitude) / 1000.0,
            "downrange_km": lerp(p0.downrange, p1.downrange) / 1000.0,
            "velocity": lerp(p0.velocity, p1.velocity),
            "v_horiz": lerp(p0.v_horiz, p1.v_horiz),
            "v_vert": lerp(p0.v_vert, p1.v_vert),
            "apoapsis_km": lerp(p0.apoapsis, p1.apoapsis),
            "periapsis_km": lerp(p0.periapsis, p1.periapsis),
            "pitch_from_vertical": lerp(p0.pitch_from_v, p1.pitch_from_v),
        }


# ---------------------------------------------------------------------------
# Phase detection
# ---------------------------------------------------------------------------

def detect_phase(state: dict, prev_phase: FlightPhase = FlightPhase.UNKNOWN) -> FlightPhase:
    """
    Infer mission phase from current telemetry state.

    Fix P1-02: Replaced the fragile `met < 70` CORE/TERRIER split with a
    three-part heuristic:
      1. Altitude + apoapsis thresholds (derived from sim data):
           CORE burnout occurs at ~15km alt, ~25km Ap.
           If alt > 17km OR Ap > 32km while burning, it's the Terrier.
      2. Hysteresis: once TERRIER is established (prev_phase), don't regress
           to CORE on apoapsis noise.
      3. COAST detection: throttle < 0.05 while airborne.

    Also adds: ORBIT detection from periapsis alone (handles post-circularize
    coasting) and proper COAST returns (was missing entirely before).
    """
    alt   = state.get("altitude")    or 0
    met   = state.get("mission_time") or 0
    solid = state.get("solid_fuel")  or 0
    liquid= state.get("liquid_fuel") or 0
    apo   = state.get("apoapsis")    or 0
    pe    = state.get("periapsis")   or 0
    throttle = state.get("throttle") or 0

    apo_km = apo  / 1000.0
    pe_km  = pe   / 1000.0
    alt_m  = alt

    # Stable orbit: periapsis above atmosphere — highest priority check
    if pe_km > 70:
        return FlightPhase.ORBIT

    # Pre-launch
    if alt_m <= 10 and met < 5:
        return FlightPhase.PRELAUNCH

    # Boosters burning
    if solid > 1:
        return FlightPhase.BOOST

    # No fuel or engines — coasting or suborbital
    if liquid < 1 or throttle < 0.05:
        return FlightPhase.COAST

    # Powered on liquid fuel -------------------------------------------------
    # Circularizing: apoapsis near target, still burning to raise periapsis
    if apo_km >= 60 and pe_km < 65:
        return FlightPhase.CIRCULARIZE

    # Orbit: ap and pe both above atmosphere (redundant with top check but clean)
    if apo_km >= 60 and pe_km >= 65:
        return FlightPhase.ORBIT

    # Ascending on liquid fuel (Ap < 60km): distinguish CORE from TERRIER
    # Hysteresis: once TERRIER phase is established, don't regress on noise
    if prev_phase in (FlightPhase.TERRIER, FlightPhase.CIRCULARIZE):
        return FlightPhase.TERRIER

    # CORE burnout is at ~15km alt, ~25km Ap (from simulation).
    # Above either threshold: Terrier has taken over.
    # Both below threshold: still on the core.
    if alt_m > 17_000 or apo_km > 32:
        return FlightPhase.TERRIER

    return FlightPhase.CORE


# ---------------------------------------------------------------------------
# Go/No-Go gate logic
# ---------------------------------------------------------------------------

def assess_gates(state: dict, phase: FlightPhase,
                 fuel_at_core_sep: Optional[float] = None) -> list[GateStatus]:
    """
    Return go/no-go assessment for all four ascent gates.
    fuel_at_core_sep: liquid fuel (units) at the moment the core was jettisoned,
                      used to compute Terrier fuel fraction. If None, estimated.
    """
    alt_km = (state.get("altitude") or 0) / 1000.0
    apo_km = (state.get("apoapsis") or 0) / 1000.0
    pe_km  = (state.get("periapsis") or 0) / 1000.0
    lf     = state.get("liquid_fuel") or 0
    met    = state.get("mission_time") or 0

    # FL-T800 LiquidFuel: 4.0t propellant at 9:11 LF:OX ratio → 1.8t LF
    # KSP unit density = 0.005 t/unit → 1.8 / 0.005 = 360 units
    # Fix P0-01: was incorrectly set to 4000 (conflated t with KSP units)
    FULL_LF = 360.0
    lf_pct = (lf / FULL_LF) * 100.0

    def gate(phase_name, go, marginal, nogo, current_val=None, units=""):
        if go:   return GateStatus(phase_name, "GO",      f"{current_val:.1f}{units}" if current_val is not None else "")
        if marginal: return GateStatus(phase_name, "MARGINAL", f"{current_val:.1f}{units}" if current_val is not None else "")
        return GateStatus(phase_name, "NO-GO", f"{current_val:.1f}{units}" if current_val is not None else "")

    gates = []

    # Gate 1: Core burnout apoapsis
    if phase in (FlightPhase.PRELAUNCH, FlightPhase.BOOST):
        gates.append(GateStatus("CORE B/O", "NOT-YET", "Awaiting booster sep"))
    else:
        # Check if apoapsis was adequately started during the core phase
        apo_ok = apo_km >= 20
        apo_marginal = apo_km >= 12
        gates.append(gate("CORE B/O", apo_ok, apo_marginal and not apo_ok, not apo_marginal,
                          apo_km, " km Ap"))

    # Gate 2: Mid-Terrier burn
    if phase in (FlightPhase.PRELAUNCH, FlightPhase.BOOST, FlightPhase.CORE):
        gates.append(GateStatus("MID-TERR", "NOT-YET", "Awaiting Terrier ignition"))
    else:
        # Apoapsis should be climbing and > 40 km if mid-burn
        apo_ok = apo_km >= 40
        apo_marginal = apo_km >= 25
        nogo = apo_km < 25 and lf_pct < 50
        gates.append(gate("MID-TERR", apo_ok, apo_marginal and not nogo, nogo, apo_km, " km Ap"))

    # Gate 3: Late Terrier burn
    if phase in (FlightPhase.PRELAUNCH, FlightPhase.BOOST, FlightPhase.CORE):
        gates.append(GateStatus("LATE-TERR", "NOT-YET", "Awaiting Terrier ignition"))
    elif lf_pct > 30:
        gates.append(GateStatus("LATE-TERR", "NOT-YET", "Mid-burn check — monitoring"))
    else:
        # Late burn: should have apoapsis ~80 km and periapsis rising
        apo_ok = apo_km >= 70
        apo_marginal = apo_km >= 50
        nogo = lf_pct < 25 and pe_km < -100
        gates.append(gate("LATE-TERR", apo_ok and not nogo, apo_marginal and not nogo, nogo,
                          pe_km, " km Pe"))

    # Gate 4: Orbit insertion
    if phase == FlightPhase.ORBIT:
        gates.append(GateStatus("INSERTION", "GO", f"Pe {pe_km:.0f} km — orbit achieved"))
    elif pe_km > 70:
        gates.append(GateStatus("INSERTION", "GO", f"Pe {pe_km:.0f} km"))
    elif pe_km > 40:
        gates.append(GateStatus("INSERTION", "MARGINAL", f"Pe {pe_km:.0f} km — trim needed"))
    elif phase in (FlightPhase.CIRCULARIZE, FlightPhase.TERRIER):
        gates.append(GateStatus("INSERTION", "NOT-YET", "Orbit not yet achieved"))
    else:
        gates.append(GateStatus("INSERTION", "NO-GO", f"Pe {pe_km:.0f} km — suborbital"))

    return gates


# ---------------------------------------------------------------------------
# Advisory generation
# ---------------------------------------------------------------------------

def generate_advisory(state: dict, phase: FlightPhase,
                       nominal: Optional[dict] = None,
                       prev_apo_km: Optional[float] = None) -> Advisory:
    """
    Generate the highest-priority correction advisory for the current state.

    Parameters
    ----------
    state : dict
        Current telemetry state snapshot.
    phase : FlightPhase
        Current mission phase (from detect_phase).
    nominal : dict, optional
        Nominal trajectory state at the same altitude or time (for pitch comparison).
    prev_apo_km : float, optional
        Apoapsis altitude (km) from the previous update cycle (~1s ago).
        If supplied, used to detect a stalling apoapsis during the Terrier burn.
        Fix P2-08: this parameter enables rate-of-change detection so a stalled
        apoapsis triggers advisory escalation before fuel is exhausted.
    """
    alt_km = (state.get("altitude") or 0) / 1000.0
    apo_km = (state.get("apoapsis") or 0) / 1000.0
    pe_km  = (state.get("periapsis") or 0) / 1000.0
    lf     = state.get("liquid_fuel") or 0
    pitch  = state.get("pitch") or 0    # deg, +up/-down from horizon in KSP
    vel    = state.get("velocity") or 0
    # Fix P0-01: FULL_LF = 360 KSP units (FL-T800 LiquidFuel; see assess_gates)
    FULL_LF = 360.0
    lf_pct = (lf / FULL_LF) * 100.0

    # ---- ABORT conditions ----
    # Fix P1-05: Guard against premature ABORT in the first seconds after Terrier ignition.
    # Core burnout is at ~63s MET; the Terrier needs ~7s to establish a valid
    # trajectory signature (Pe and Ap responding to the burn). Below MET=70,
    # Pe is still deeply negative and Ap low by design — these are not abort criteria.
    # The fuel reading can also lag at ignition. Guard until MET>70.
    MET_TERRIER_ESTABLISHED = 70.0
    terrier_established = (state.get("mission_time") or 0) > MET_TERRIER_ESTABLISHED
    if phase == FlightPhase.TERRIER and terrier_established \
            and lf_pct < 25 and pe_km < -100 and apo_km < 40:
        return Advisory(
            level="ABORT",
            action="EXECUTE ABORT",
            reason=f"Apoapsis {apo_km:.0f} km stalled, Pe {pe_km:.0f} km, "
                   f"fuel {lf_pct:.0f}% — insufficient for orbit",
            urgent=True,
        )

    # ---- TERRIER ascent guidance ----
    if phase == FlightPhase.TERRIER:
        # Main risk: flying too steep — apoapsis not rising
        if apo_km < 30 and alt_km > 15 and lf_pct < 60:
            return Advisory(
                level="WARNING",
                action="PITCH TOWARD HORIZON",
                reason=f"Apoapsis {apo_km:.0f} km — build horizontal speed, lower the nose",
                urgent=True,
            )
        if apo_km < 50 and lf_pct < 40:
            return Advisory(
                level="CAUTION",
                action="PITCH TOWARD HORIZON",
                reason=f"Apoapsis {apo_km:.0f} km, fuel {lf_pct:.0f}% — need more horizontal speed",
            )
        if apo_km > 90 and pe_km < 60:
            return Advisory(
                level="CAUTION",
                action="FLATTEN PITCH — APOAPSIS HIGH",
                reason=f"Apoapsis {apo_km:.0f} km (target 80) — ease off climb, build periapsis",
            )
        if apo_km >= 70 and pe_km > 50:
            return Advisory(
                level="NOMINAL",
                action="MAINTAIN PROGRADE",
                reason=f"Apoapsis {apo_km:.0f} km, periapsis rising — on track for orbit",
            )

        # Apoapsis stall detection (P2-08): if prev_apo_km is available,
        # compute the rate. A stalling or falling apoapsis mid-burn is more
        # concerning than a low absolute value that's still rising.
        if prev_apo_km is not None:
            apo_rate = apo_km - prev_apo_km    # km gained since last update
            if apo_km < 50 and apo_rate <= 0.0 and lf_pct < 70:
                return Advisory(
                    level="WARNING",
                    action="PITCH TOWARD HORIZON — APOAPSIS STALLING",
                    reason=(f"Apoapsis {apo_km:.0f} km not rising "
                            f"(Δ{apo_rate:+.1f} km), fuel {lf_pct:.0f}% — "
                            f"need more horizontal speed"),
                    urgent=True,
                )

        # Compare to nominal pitch if we have it
        if nominal:
            nom_pitch_v = nominal.get("pitch_from_vertical", None)
            if nom_pitch_v is not None:
                # KSP pitch is from horizon; pitch_from_vertical = 90 - KSP_pitch
                actual_pitch_v = 90.0 - pitch
                diff = actual_pitch_v - nom_pitch_v
                if diff > 12:
                    return Advisory(
                        level="CAUTION",
                        action=f"PITCH TOWARD HORIZON  (+{diff:.0f}° STEEP)",
                        reason=(f"Flying {diff:.0f}° steeper than nominal — "
                                f"gaining altitude at cost of horizontal speed"),
                    )
                elif diff < -12:
                    return Advisory(
                        level="CAUTION",
                        action=f"PITCH TOWARD VERTICAL  ({-diff:.0f}° SHALLOW)",
                        reason=(f"Flying {-diff:.0f}° shallower than nominal — "
                                f"may undershoot apoapsis target"),
                    )

        return Advisory("NOMINAL", "MAINTAIN PROGRADE",
                        f"Apoapsis {apo_km:.0f} km — climbing toward target")

    # ---- Circularize ----
    if phase == FlightPhase.CIRCULARIZE:
        if pe_km < 60:
            return Advisory(
                level="CAUTION",
                action="BURN PROGRADE — LEAD APOAPSIS",
                reason=f"Pe {pe_km:.0f} km — start burn {2} s before Ap, burn until Pe ~80 km",
            )
        return Advisory("NOMINAL", "MAINTAINING ORBIT",
                        f"Pe {pe_km:.0f} km, Ap {apo_km:.0f} km")

    # ---- Boost / Core ----
    if phase in (FlightPhase.BOOST, FlightPhase.CORE):
        return Advisory("NOMINAL", "FOLLOW PITCH PROGRAM",
                        f"h={alt_km:.1f} km v={vel:.0f} m/s — nominal ascent")

    return Advisory("NOMINAL", "STANDING BY", f"Phase: {phase.value}")


# ---------------------------------------------------------------------------
# FlightDirector: main interface
# ---------------------------------------------------------------------------

class FlightDirector:
    """
    Combines gate assessment and advisory generation into a single callable.
    Maintains a small amount of state (previous phase, fuel at core sep).

    Usage::

        fd = FlightDirector(nominal)
        # On each telemetry update:
        result = fd.update(state)
        # result = {
        #   'phase': 'TERRIER',
        #   'advisory': {'level': 'CAUTION', 'action': '...', 'reason': '...'},
        #   'gates': [{'phase': '...', 'status': '...', 'detail': '...'}, ...],
        #   'nominal_at_alt': {...},
        # }
    """

    def __init__(self, nominal: NominalTrajectory):
        self.nominal = nominal
        self._phase = FlightPhase.PRELAUNCH
        self._fuel_at_core_sep: Optional[float] = None
        self._prev_apo_km: Optional[float] = None   # for P2-08 stall detection

    def update(self, state: dict) -> dict:
        """Process one telemetry snapshot and return the full director output."""
        phase = detect_phase(state, self._phase)

        # Track fuel at the moment we transition from CORE to TERRIER
        if self._phase == FlightPhase.CORE and phase == FlightPhase.TERRIER:
            self._fuel_at_core_sep = state.get("liquid_fuel")

        self._phase = phase

        met = state.get("mission_time") or 0
        alt = state.get("altitude") or 0
        nominal_at_t   = self.nominal.at_time(met)
        nominal_at_alt = self.nominal.at_altitude(alt)

        gates = assess_gates(state, phase, self._fuel_at_core_sep)
        advisory = generate_advisory(state, phase, nominal_at_alt,
                                     prev_apo_km=self._prev_apo_km)

        # Update prev_apo for next cycle
        self._prev_apo_km = (state.get("apoapsis") or 0) / 1000.0

        return {
            "phase": phase.value,
            "advisory": {
                "level":  advisory.level,
                "action": advisory.action,
                "reason": advisory.reason,
                "urgent": advisory.urgent,
            },
            "gates": [
                {"phase": g.phase, "status": g.status, "detail": g.detail}
                for g in gates
            ],
            "nominal_at_time": nominal_at_t,
            "nominal_at_alt":  nominal_at_alt,
        }
